--- 
version: "3.2"
services: 
  murmur: 
    build: .
    container_name: murmur
    command: service mumble-server restart
    restart: always
    ports: 
      - "64738:64738"
    env_file: .env
    volumes: 
      - .:/home/murmur/data
