--- 
version: "3.2"
services: 
  murmur: 
    build: .
    container_name: murmur
    privileged: true
    cap_add:
        - SYS_ADMIN
        - DAC_READ_SEARCH
    command: sh /opt/mumble/run.sh
    restart: always
    ports: 
      - "64738:64738"
    env_file: .env
    volumes: 
      - murmur_data:/etc/mumble
