--- 
version: "3.2"
services: 
  murmur: 
    build: .
    container_name: murmur
    privileged: true
    command: murmurd
    restart: always
    ports: 
      - "64735:64738"
      - "64735:64738/udp"
    env_file: .env
    volumes: 
      - .:/home/murmur/data
