version: '3.2'

services:
  mumble:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/var/lib/murmur/:rw
    ports:
      - 6502:6502
      - 64738:64738
      - 64738:64738/udp

volumes:
  data: